ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'

Vagrant.configure("2") do |config|

  config.vm.define "mesos" do |app|
    app.vm.provider "docker" do |d|
      #d.image = "mesosphere/mesos-master:0.20.0"
      d.image = "redjack/mesos-master:latest"
      d.cmd   = ["mesos-master", "-p 5050:5050"]
    end
  end
end